// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCiHP1cE8t1zyCPHxJpX01QQ3l5B8j5K8',
    appId: '1:54453482014:web:d672cf9134e0ae2efc340f',
    messagingSenderId: '54453482014',
    projectId: 'mymobileauth-c7436',
    authDomain: 'mymobileauth-c7436.firebaseapp.com',
    storageBucket: 'mymobileauth-c7436.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClmJ9dI9zZG_WJ8bijre6fWst6dJypiAw',
    appId: '1:54453482014:android:fcd137def5a91084fc340f',
    messagingSenderId: '54453482014',
    projectId: 'mymobileauth-c7436',
    storageBucket: 'mymobileauth-c7436.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP4LDf2dAHM5IfubZ1gWRUpp6BAti-6qo',
    appId: '1:54453482014:ios:9d890568d36e823bfc340f',
    messagingSenderId: '54453482014',
    projectId: 'mymobileauth-c7436',
    storageBucket: 'mymobileauth-c7436.appspot.com',
    androidClientId: '54453482014-du018pcgh173h26bp340k2n56kjojum5.apps.googleusercontent.com',
    iosClientId: '54453482014-u797mf4ik24us1tf0l6hbuluisobbhuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP4LDf2dAHM5IfubZ1gWRUpp6BAti-6qo',
    appId: '1:54453482014:ios:9d890568d36e823bfc340f',
    messagingSenderId: '54453482014',
    projectId: 'mymobileauth-c7436',
    storageBucket: 'mymobileauth-c7436.appspot.com',
    androidClientId: '54453482014-du018pcgh173h26bp340k2n56kjojum5.apps.googleusercontent.com',
    iosClientId: '54453482014-u797mf4ik24us1tf0l6hbuluisobbhuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppClone',
  );
}
